apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-price
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-price
  template:
    metadata:
      labels:
        app: mysql-price
    spec:
      containers:
        - name: mysql-price
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: price_db
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-price
spec:
  selector:
    app: mysql-price
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
