server:
  port: 8082

spring:
  application:
    name: price-service
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql-price}:${DB_PORT:3306}/${DB_NAME:price_db}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-registry:8761/eureka}

ml:
  price-service:
    base-url: ${ML_PRICE_SERVICE_URL:http://ml-price-service:8000}
    connect-timeout-ms: ${ML_PRICE_SERVICE_CONNECT_TIMEOUT_MS:2000}
    read-timeout-ms: ${ML_PRICE_SERVICE_READ_TIMEOUT_MS:3000}
