server:
  port: 8083

spring:
  application:
    name: weather-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-registry:8761/eureka}

openweathermap:
  api-key: ${OPENWEATHERMAP_API_KEY:}
